### PR TITLE
Update collection-hooks version

### PR DESCRIPTION
**Pull request by Floriferous**

### CODE REVIEW

**Comment by Floriferous** [comment]
@Herteby Could this be merged?

**Comment by Herteby** [comment]
@Floriferous Hi! I haven't been working with Meteor for 3 years, and I'm looking for someone to take over ownership of the package. Would you like to?

I'm not sure what the best way of doing it is. I know I can transfer ownership of the Git repo, but I'm guessing there's no such option for Atmosphere. Maybe the best would simply be if I edit the README to mark it as deprecated, and you publish your fork as a new package? I can also create an issue for Grapher to switch over to your fork. How does that sound? 🙂

**Comment by Floriferous** [comment]
I think you can help here :)

https://github.com/Meteor-Community-Packages/organization/issues/44

**Comment by StorytellerCZ** [comment]
Superseded by #26

**Pull request closed without merging**
